package com.vincent.tools.dict.domain;

public enum DictErrorCode {
    INVALID_ARGUMENT,
    DICT_NOT_FOUND,
    DICT_CODE_CONFLICT,
    DICT_NOT_EMPTY,
    DICT_ITEM_NOT_FOUND,
    DICT_ITEM_CODE_CONFLICT,
    DICT_ITEM_LIMIT_EXCEEDED,
    TENANT_CONTEXT_MISSING,
    TENANT_NOT_FOUND,
    DEFAULT_ITEM_PROTECTED,
    PERMISSION_DENIED,
    OPTIMISTIC_LOCK_CONFLICT,
    SCHEMA_MISSING,
    SCHEMA_VERSION_MISMATCH,
    CONFIGURATION_INVALID
}
